# The Travis magic
language: perl
perl:
  - "5.16"

install:
    - cpanm --quiet Dist::Zilla
    - dzil authordeps --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
script:
  - dzil smoke --release --author